/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arthu
 */
public class CadCliente_GUI extends javax.swing.JFrame {
    
    String servidor = "localhost";
    String banco = "mercado";
    String url = "jdbc:mysql://localhost/mercado";
    String usuario = "root";
    String senhaBanco = "ceap";
    String nom = "";
    long tel = 0;
    long cpf = 0;
    
    public CadCliente_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tel_Cliente = new org.edisoncor.gui.textField.TextFieldRectImage();
        nome_Cliente = new org.edisoncor.gui.textField.TextFieldRectImage();
        cpf_Cliente = new org.edisoncor.gui.textField.TextFieldRectImage();
        Voltar_btn = new org.edisoncor.gui.button.ButtonTextDown();
        Cadastro_btn1 = new org.edisoncor.gui.button.ButtonTextDown();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setColorPrimario(new java.awt.Color(0, 51, 255));
        panel1.setColorSecundario(new java.awt.Color(0, 0, 153));
        panel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE CLIENTES");
        panel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 370, 35);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone");
        panel1.add(jLabel2);
        jLabel2.setBounds(40, 270, 70, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        panel1.add(jLabel3);
        jLabel3.setBounds(40, 126, 60, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF");
        panel1.add(jLabel4);
        jLabel4.setBounds(40, 200, 70, 20);
        panel1.add(tel_Cliente);
        tel_Cliente.setBounds(120, 270, 300, 30);
        panel1.add(nome_Cliente);
        nome_Cliente.setBounds(120, 120, 300, 30);
        panel1.add(cpf_Cliente);
        cpf_Cliente.setBounds(120, 190, 300, 30);

        Voltar_btn.setForeground(new java.awt.Color(0, 0, 0));
        Voltar_btn.setText("VOLTAR");
        Voltar_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Voltar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar_btnActionPerformed(evt);
            }
        });
        panel1.add(Voltar_btn);
        Voltar_btn.setBounds(320, 390, 107, 50);

        Cadastro_btn1.setForeground(new java.awt.Color(0, 0, 0));
        Cadastro_btn1.setText("CADASTRAR");
        Cadastro_btn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Cadastro_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_btn1ActionPerformed(evt);
            }
        });
        panel1.add(Cadastro_btn1);
        Cadastro_btn1.setBounds(120, 390, 146, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(569, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar_btnActionPerformed
        dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_Voltar_btnActionPerformed

    private void Cadastro_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_btn1ActionPerformed
        //--- Codigo
        
        nom = nome_Cliente.getText(); // recebendo o nome
        cpf = Long.valueOf(cpf_Cliente.getText());// recebendo o email
        tel = Long.valueOf(tel_Cliente.getText());// recebendo o telefone
      

        Controller.Conecta_BD.carregaDriver();
       
        try { 
               
                   
            
            Connection con = null;
            
            
        try {
            con = (Connection) DriverManager.getConnection(url, usuario, senhaBanco);
        } catch (SQLException ex) {

            Logger.getLogger(CadCliente_GUI.class.getName()).log(Level.SEVERE, null, ex);

            
        }

            // Recebendo os dados a serem inseridos na tabela
            String sql = "INSERT INTO cliente(cpf_cli, nome_cli, tel_cli) values('"+cpf+"','"+nom+"','"+tel+"')";
     
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

                JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                nome_Cliente.setText("");
                cpf_Cliente.setText("");
                tel_Cliente.setText("");
                
                sleep(2000);
                dispose();
                new Menu_GUI().setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

            }catch(NumberFormatException erro){
                // Tratamento de erro caso o usuario não digite o telefone corretamente
                JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
                tel_Cliente.setText("");
            }

       
              

        
        //--- Fim codigo
    }//GEN-LAST:event_Cadastro_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTextDown Cadastro_btn1;
    private org.edisoncor.gui.button.ButtonTextDown Voltar_btn;
    private org.edisoncor.gui.textField.TextFieldRectImage cpf_Cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.textField.TextFieldRectImage nome_Cliente;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.textField.TextFieldRectImage tel_Cliente;
    // End of variables declaration//GEN-END:variables
}
