/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arthu
 */
public class VisuCompra_GUI extends javax.swing.JFrame {
    
    String servidor = "localhost";
    String banco = "mercado";
    String url = "jdbc:mysql://localhost/mercado";
    String usuario = "root";
    String senhaBanco = "ceap";
    public static String forma = "";
    
      //inicio codigo
    
    public static DefaultTableModel  compra(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("CPF");
            columnNames.addElement("Cliente");
            columnNames.addElement("Item");
             columnNames.addElement("QTDE");
            columnNames.addElement("Data");
            columnNames.addElement("Preço (UN)");
            columnNames.addElement("Total");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
       }
    }
    
     public void refresh(){
    
        try{
           Connection conn;
           conn = (Connection) DriverManager.getConnection(url, usuario, senhaBanco);
           Controller.Conecta_BD.carregaDriver();


           System.out.println("realizado");
           String sql = "SELECT * FROM compra;";
           PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
           ResultSet rs = pst.executeQuery();
           compras.setModel(compra(rs));
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }    
    } 



    
    
    //fim codigo

    /**
     * Creates new form VisuCompra_GUI
     */
    public VisuCompra_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("mercado?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        compraQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Compra c");
        compraList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : compraQuery.getResultList();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        compras = new javax.swing.JTable();
        dinheiro_btn = new org.edisoncor.gui.button.ButtonAction();
        debito_btn = new org.edisoncor.gui.button.ButtonAction();
        credito_btn = new org.edisoncor.gui.button.ButtonAction();
        pix_btn = new org.edisoncor.gui.button.ButtonAction();
        jLabel1 = new javax.swing.JLabel();
        cod = new org.edisoncor.gui.textField.TextField();
        jLabel2 = new javax.swing.JLabel();
        cpf = new org.edisoncor.gui.textField.TextField();
        jLabel3 = new javax.swing.JLabel();
        cliente = new org.edisoncor.gui.textField.TextField();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonAction5 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction6 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction7 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction8 = new org.edisoncor.gui.button.ButtonAction();
        jLabel4 = new javax.swing.JLabel();
        textField4 = new org.edisoncor.gui.textField.TextField();
        jLabel5 = new javax.swing.JLabel();
        textField5 = new org.edisoncor.gui.textField.TextField();
        jLabel6 = new javax.swing.JLabel();
        textField6 = new org.edisoncor.gui.textField.TextField();
        jLabel7 = new javax.swing.JLabel();
        item = new org.edisoncor.gui.textField.TextField();
        jLabel8 = new javax.swing.JLabel();
        qtde = new org.edisoncor.gui.textField.TextField();
        jLabel9 = new javax.swing.JLabel();
        preco_ind = new org.edisoncor.gui.textField.TextField();
        jLabel10 = new javax.swing.JLabel();
        total = new org.edisoncor.gui.textField.TextField();
        Nota_btn = new org.edisoncor.gui.button.ButtonNice();
        Excluir_btn = new org.edisoncor.gui.button.ButtonTextDown();
        Consulta_btn = new org.edisoncor.gui.button.ButtonTextDown();
        Alterar_btn = new org.edisoncor.gui.button.ButtonTextDown();
        Atualizar_btn = new org.edisoncor.gui.button.ButtonTextDown();
        buttonNice1 = new org.edisoncor.gui.button.ButtonNice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setColorPrimario(new java.awt.Color(0, 0, 255));
        panel1.setColorSecundario(new java.awt.Color(0, 0, 153));
        panel1.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, compraList, compras);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCom}"));
        columnBinding.setColumnName("Código ");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpfCom}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliCom}"));
        columnBinding.setColumnName("Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${prodCom}"));
        columnBinding.setColumnName("Item");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${qtdeCom}"));
        columnBinding.setColumnName("QTDE");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataCom}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoInd}"));
        columnBinding.setColumnName("Preço (UN)");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoFin}"));
        columnBinding.setColumnName("Total");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(compras);
        if (compras.getColumnModel().getColumnCount() > 0) {
            compras.getColumnModel().getColumn(1).setPreferredWidth(120);
            compras.getColumnModel().getColumn(2).setPreferredWidth(120);
            compras.getColumnModel().getColumn(5).setPreferredWidth(100);
            compras.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 570, 70);

        dinheiro_btn.setText("DINHEIRO");
        dinheiro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiro_btnActionPerformed(evt);
            }
        });
        panel1.add(dinheiro_btn);
        dinheiro_btn.setBounds(460, 150, 80, 50);

        debito_btn.setText("DÉBITO");
        debito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debito_btnActionPerformed(evt);
            }
        });
        panel1.add(debito_btn);
        debito_btn.setBounds(360, 90, 70, 50);

        credito_btn.setText("CRÉDITO");
        credito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credito_btnActionPerformed(evt);
            }
        });
        panel1.add(credito_btn);
        credito_btn.setBounds(460, 90, 80, 50);

        pix_btn.setText("PIX");
        pix_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pix_btnActionPerformed(evt);
            }
        });
        panel1.add(pix_btn);
        pix_btn.setBounds(360, 150, 70, 50);

        jLabel1.setText("Código da Compra");
        panel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 120, 16);
        panel1.add(cod);
        cod.setBounds(10, 100, 70, 30);

        jLabel2.setText("CPF");
        panel1.add(jLabel2);
        jLabel2.setBounds(10, 140, 120, 16);
        panel1.add(cpf);
        cpf.setBounds(10, 160, 150, 30);

        jLabel3.setText("Cliente");
        panel1.add(jLabel3);
        jLabel3.setBounds(10, 200, 120, 16);
        panel1.add(cliente);
        cliente.setBounds(10, 220, 150, 30);

        panel2.setColorPrimario(new java.awt.Color(0, 0, 255));
        panel2.setColorSecundario(new java.awt.Color(0, 0, 153));
        panel2.setLayout(null);

        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        panel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 570, 70);

        buttonAction5.setText("DINHEIRO");
        panel2.add(buttonAction5);
        buttonAction5.setBounds(440, 260, 116, 50);

        buttonAction6.setText("DÉBITO");
        panel2.add(buttonAction6);
        buttonAction6.setBounds(440, 80, 116, 50);

        buttonAction7.setText("CRÉDITO");
        panel2.add(buttonAction7);
        buttonAction7.setBounds(440, 140, 116, 50);

        buttonAction8.setText("PIX");
        panel2.add(buttonAction8);
        buttonAction8.setBounds(440, 200, 116, 50);

        jLabel4.setText("Código da Compra");
        panel2.add(jLabel4);
        jLabel4.setBounds(10, 80, 120, 16);
        panel2.add(textField4);
        textField4.setBounds(10, 100, 70, 30);

        jLabel5.setText("CPF");
        panel2.add(jLabel5);
        jLabel5.setBounds(10, 140, 120, 16);
        panel2.add(textField5);
        textField5.setBounds(10, 160, 150, 30);

        jLabel6.setText("Cliente");
        panel2.add(jLabel6);
        jLabel6.setBounds(10, 200, 120, 16);
        panel2.add(textField6);
        textField6.setBounds(10, 220, 150, 30);

        panel1.add(panel2);
        panel2.setBounds(0, 0, 0, 0);

        jLabel7.setText("Item da Compra");
        panel1.add(jLabel7);
        jLabel7.setBounds(10, 260, 120, 16);
        panel1.add(item);
        item.setBounds(10, 280, 150, 30);

        jLabel8.setText("QTDE");
        panel1.add(jLabel8);
        jLabel8.setBounds(10, 320, 120, 16);
        panel1.add(qtde);
        qtde.setBounds(10, 340, 60, 30);

        jLabel9.setText("Preço por Unidade");
        panel1.add(jLabel9);
        jLabel9.setBounds(10, 380, 120, 16);
        panel1.add(preco_ind);
        preco_ind.setBounds(10, 400, 150, 30);

        jLabel10.setText("Total");
        panel1.add(jLabel10);
        jLabel10.setBounds(10, 440, 120, 16);
        panel1.add(total);
        total.setBounds(10, 460, 150, 30);

        Nota_btn.setText("NOTA FISCAL");
        Nota_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Nota_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nota_btnActionPerformed(evt);
            }
        });
        panel1.add(Nota_btn);
        Nota_btn.setBounds(380, 440, 150, 60);

        Excluir_btn.setForeground(new java.awt.Color(0, 0, 0));
        Excluir_btn.setText("EXCLUIR");
        Excluir_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_btnActionPerformed(evt);
            }
        });
        panel1.add(Excluir_btn);
        Excluir_btn.setBounds(400, 370, 130, 40);

        Consulta_btn.setForeground(new java.awt.Color(0, 0, 0));
        Consulta_btn.setText("CONSULTAR");
        Consulta_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Consulta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta_btnActionPerformed(evt);
            }
        });
        panel1.add(Consulta_btn);
        Consulta_btn.setBounds(400, 220, 130, 40);

        Alterar_btn.setForeground(new java.awt.Color(0, 0, 0));
        Alterar_btn.setText("ALTERAR");
        Alterar_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Alterar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar_btnActionPerformed(evt);
            }
        });
        panel1.add(Alterar_btn);
        Alterar_btn.setBounds(400, 270, 130, 40);

        Atualizar_btn.setForeground(new java.awt.Color(0, 0, 0));
        Atualizar_btn.setText("ATUALIZAR");
        Atualizar_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Atualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atualizar_btnActionPerformed(evt);
            }
        });
        panel1.add(Atualizar_btn);
        Atualizar_btn.setBounds(400, 320, 130, 40);

        buttonNice1.setText("VOLTAR");
        buttonNice1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonNice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNice1ActionPerformed(evt);
            }
        });
        panel1.add(buttonNice1);
        buttonNice1.setBounds(200, 440, 160, 64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(569, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Nota_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nota_btnActionPerformed
        Model.GerarPDF_DAO.ConsultaDados();
        try {
            Model.GerarPDF_DAO.GeraNota();
        } catch (IOException ex) {
            Logger.getLogger(VisuCompra_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(VisuCompra_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Nota_btnActionPerformed

    private void Consulta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta_btnActionPerformed
        //incio codigo
        
        try{     //Iniciando o possivel tratamento de erros
            //Declarando a variavel código
            int codCom = Integer.valueOf(cod.getText());
            Controller.Conecta_BD.carregaDriver(); // Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                con = (Connection) DriverManager.getConnection(url,usuario,senhaBanco);

                // Declarando uma string com o comando mySQL para consulta
                String sql = "SELECT cpf_com, cli_com, prod_com, preco_ind, qtde_com, preco_fin FROM compra WHERE id_com ="+codCom;
                // Criando variavel que executara o comando da string sql
                Statement stm = (Statement) con.createStatement();
                try//Tratamento de erro da consulta
                { //Criando variavel que exibira os resultados
                    //Executando o comando da string sql na variavel rs
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; // Variavel utilizada para saber se ha dados cadastrados

                    while (rs.next()) {  // Criando variaveis que receberão os valores do banco de dados
                        String cpf2 = rs.getString("cpf_com");
                        String cliente2 = rs.getString("cli_com");
                        String produto = rs.getString("prod_com");
                        String precoInd = rs.getString("preco_ind");
                        String qtde2 = rs.getString("qtde_com");
                        String precoFin = rs.getString("preco_fin");

                        i++;

                        //JOptionPane.showMessageDialog(null,"Nome: " + nome + "\nEmail: " +email + "\nTelefone: " +telefone, "Resultado",-1);
                        cpf.setText(String.valueOf(cpf2));
                        cliente.setText(String.valueOf(cliente2));
                        item.setText(String.valueOf(produto));
                        qtde.setText(String.valueOf(qtde2));
                        preco_ind.setText(String.valueOf(precoInd));
                        total.setText(String.valueOf(precoFin));

                    }

                    if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        JOptionPane.showMessageDialog(null,"Dado não cadastrado","Resultado",-1);

                    }

                } catch (Exception ex) { // Consulta mal sucedida
                    JOptionPane.showMessageDialog(null,"\nErro ao consultar!","ERRO",0);
                }

            } catch (SQLException ex) {
                // Conexão com servidor mal sucedida
                JOptionPane.showMessageDialog(null,"Erro ao conectar com o servidor","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cod.setText("");
        }
        //fim codigo
    }//GEN-LAST:event_Consulta_btnActionPerformed

    private void Alterar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar_btnActionPerformed
        // inicio do codigo
        
        long cpf2 = Long.valueOf(cpf.getText()); // recebendo o nome
        String cliente2 = cliente.getText(); // recebendo o email
        String prod = item.getText(); // recebendo o nome
        int qtde2 = Integer.parseInt(qtde.getText()); // recebendo o email
        float precoInd = Float.parseFloat(preco_ind.getText()); // recebendo o email  
        float total2 = Float.parseFloat(total.getText());




        Controller.Conecta_BD.carregaDriver();
       
        try {     
              Connection con = null;
        try {
              con = (Connection) DriverManager.getConnection(url, usuario, senhaBanco);
        }catch (SQLException ex) {
              Logger.getLogger(VisuCompra_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
              String sql = "UPDATE compra SET cpf_com='"+cpf2+"',cli_com='"+cliente2+"',prod_com='"+prod+"',qtde_com='"+qtde2+"',preco_ind='"+precoInd+"',preco_fin='"+total2+"' WHERE id_com="+cod.getText();


              try { 
                  PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                  inserir.execute(); // Executando a inserção

                  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                  cpf.setText("");
                  cliente.setText("");
                  item.setText("");
                  qtde.setText("");
                  preco_ind.setText("");
                  total.setText("");
              } catch (Exception ex) {
                  JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
              }

          }catch(NumberFormatException erro){
              // Tratamento de erro caso o usuario não digite o telefone corretamente
              JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
              cod.setText("");
              preco_ind.setText("");
              total.setText("");
          }
        // fim do codigo
    }//GEN-LAST:event_Alterar_btnActionPerformed

    private void Atualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atualizar_btnActionPerformed
        refresh();
    }//GEN-LAST:event_Atualizar_btnActionPerformed

    private void Excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_btnActionPerformed
        // inicio codigo
        
        Controller.Conecta_BD.carregaDriver(); // Carregando o driver


       //int codigo = Integer.valueOf(cod_Funcionario.getText()); // Recebendo o código

                

        try {// Tratamento de erro para a conexao
            // Declarando  a variavel de conexão con
            // e estabelendo a conexão
            Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url, usuario, senhaBanco);
                } catch (SQLException ex) {
                    Logger.getLogger(VisuCompra_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
           

            // Criando String com comando SQL para exclusão
            String sql = "DELETE FROM compra WHERE id_com ="+cod.getText();;

            try // Tratamento de erros para exclusão
            {// Criando Variavel para executar a ação
                PreparedStatement excluir = (PreparedStatement) con.prepareStatement(sql);
                excluir.execute();// Executando a exclusão

                JOptionPane.showMessageDialog(null,"\nExclusão realizada com sucesso!!!\n","",-1);
                cod.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na exclusão!","ERRO!",0);
            }

        } catch(NumberFormatException erro){ // Codigo digitado com caracteres não numericos
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cod.setText("");

        }
        
        //fim codigo
    }//GEN-LAST:event_Excluir_btnActionPerformed

    private void debito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debito_btnActionPerformed
        forma = "DÉBITO";
    }//GEN-LAST:event_debito_btnActionPerformed

    private void credito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credito_btnActionPerformed
       forma = "CRÉDITO";
    }//GEN-LAST:event_credito_btnActionPerformed

    private void pix_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pix_btnActionPerformed
        forma = "PIX";
    }//GEN-LAST:event_pix_btnActionPerformed

    private void dinheiro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiro_btnActionPerformed
        forma = "DINHEIRO";
    }//GEN-LAST:event_dinheiro_btnActionPerformed

    private void buttonNice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNice1ActionPerformed
        dispose();
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_buttonNice1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuCompra_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuCompra_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuCompra_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuCompra_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisuCompra_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTextDown Alterar_btn;
    private org.edisoncor.gui.button.ButtonTextDown Atualizar_btn;
    private org.edisoncor.gui.button.ButtonTextDown Consulta_btn;
    private org.edisoncor.gui.button.ButtonTextDown Excluir_btn;
    private org.edisoncor.gui.button.ButtonNice Nota_btn;
    private org.edisoncor.gui.button.ButtonAction buttonAction5;
    private org.edisoncor.gui.button.ButtonAction buttonAction6;
    private org.edisoncor.gui.button.ButtonAction buttonAction7;
    private org.edisoncor.gui.button.ButtonAction buttonAction8;
    private org.edisoncor.gui.button.ButtonNice buttonNice1;
    private org.edisoncor.gui.textField.TextField cliente;
    private org.edisoncor.gui.textField.TextField cod;
    private java.util.List<View.Compra> compraList;
    private javax.persistence.Query compraQuery;
    private javax.swing.JTable compras;
    private org.edisoncor.gui.textField.TextField cpf;
    private org.edisoncor.gui.button.ButtonAction credito_btn;
    private org.edisoncor.gui.button.ButtonAction debito_btn;
    private org.edisoncor.gui.button.ButtonAction dinheiro_btn;
    private javax.persistence.EntityManager entityManager;
    private org.edisoncor.gui.textField.TextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.button.ButtonAction pix_btn;
    private org.edisoncor.gui.textField.TextField preco_ind;
    private org.edisoncor.gui.textField.TextField qtde;
    private org.edisoncor.gui.textField.TextField textField4;
    private org.edisoncor.gui.textField.TextField textField5;
    private org.edisoncor.gui.textField.TextField textField6;
    private org.edisoncor.gui.textField.TextField total;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
